[package]
name = "stealth-studios/stealth-sdk"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ratelimit = "red-blox/ratelimit@1.0.1"
fusion = "elttob/fusion@0.3.0"
