[package]
include = [
    "dist",
    "dist/client",
    "dist/client/**",
    "dist/server",
    "dist/server/**",
    "dist/**.luau",
    "default.project.json",
    "wally.lock",
    "wally.toml",
    "README.md",
]
name = "stealth-studios/stealth-sdk"
version = "1.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]

[dependencies]
ratelimit = "red-blox/ratelimit@1.0.1"
fusion = "elttob/fusion@0.3.0"