[package]
name = "stealth-studios/stealth-sdk"
version = "1.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = [
    "dist",
    "dist/**",
    "default.project.json",
    "wally.lock",
    "wally.toml",
    "README.md",
]

[dependencies]
ratelimit = "red-blox/ratelimit@1.0.1"
fusion = "elttob/fusion@0.3.0"
